### ISSUE TITLE
Multiline components break highlighting after component

### ISSUE THREAD

**Issue by chrisvfritz** [Guidebook/sublime-cjsx#2]
For example:

``` cjsx
<MyComponent
  key  = { @props.id   }
  attr = { @props.attr }
/>
```

Everything after the component seems to be parsed as component attributes.

**Comment by kwood** [comment]
I believe this is actually related to the self-closing tag, so this should now be fixed. Please reopen with a screenshot if I'm mistaken.

**Comment by chrisvfritz** [comment]
Also fixed! :smiley: :metal:
