### ISSUE TITLE
Underscores not properly parsed in attribute names

### ISSUE THREAD

**Issue by chrisvfritz** [Guidebook/sublime-cjsx#3]
Although underscores are valid in attribute names, such as in `my_attribute`, the `_attribute` part of that will not be correctly highlighted.

**Comment by kwood** [comment]
Hi @chrisvfritz 

Thanks for the report -- can you test out the change in 1bbae9a ?

**Comment by kwood** [comment]
I went ahead and shipped a release with this fix

**Comment by chrisvfritz** [comment]
This does indeed look fixed. :smiley: :tada:
